[package]
name = "simpos"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.8.0"
eframe = "0.29.1"
egui = "0.29.1"
egui_plot = "0.29.0"
env_logger = "0.11.5"
log = "0.4.22"
serialport = "4.6.0"

[profile.dev]
opt-level = 3
